Update chart-wrapper.component.ts
FERNman/angular-google-charts pull request #185
Opened 2020-12-08 18:47 UTC by frsab

fix https://github.com/FERNman/angular-google-charts/issues/173

2021-01-16 09:35 UTC, FERNman approved these changes

2021-01-16 09:46 UTC, FERNman requested changes

2021-01-16 09:46 UTC, FERNman commented on libs/angular-google-charts/src/lib/components/chart-wrapper/chart-wrapper.component.ts
> +  public set chartWrapper(wrapper: google.visualization.ChartBase | undefined) {
This doesn't compile when using TS strict mode. Can you explain the reasoning behind this change?

2021-02-22 19:11 UTC, kussmaul commented
I think we need to change the type for `set chartWrapper`, `get chartWrapper`, _and_ ChartBase.chartWrapper, e.g.:
https://github.com/kussmaul/angular-google-charts/commit/bf3a194e49a55fbbda2bef188e5bc02df44e89eb

2021-02-24 19:10 UTC, kussmaul commented
Everything works for me with Angular-google-charts@2.0.1.
(My previous comment was for an earlier version. Sorry for the confusion.

2021-02-25 07:56 UTC, FERNman commented
Closing as per @kussmaul's comment

2021-02-25 07:56 UTC, closed without merging